# Generated by Django 4.2.6 on 2023-10-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
                ('BrandId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ColorName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(max_length=50)),
                ('MobileNumber', models.CharField(max_length=11)),
                ('Email', models.CharField(max_length=100)),
                ('Address1', models.CharField(max_length=200)),
                ('Address2', models.CharField(max_length=200)),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('u_dt', models.DateTimeField(auto_now_add=True)),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.area')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistrictName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(max_length=8)),
                ('ProductName', models.CharField(max_length=100)),
                ('UnitPreviousStock', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('UnitStockInHand', models.IntegerField()),
                ('Image', models.ImageField(upload_to='product_image/')),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('u_dt', models.DateTimeField(auto_now_add=True)),
                ('u_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitQty', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
            ],
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThanaName', models.CharField(max_length=200)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SizeName', models.CharField(max_length=50)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
            ],
        ),
        migrations.CreateModel(
            name='SaleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaleInvoiceNumber', models.CharField(max_length=150)),
                ('Qty', models.IntegerField()),
                ('TotalPurchasePrice', models.IntegerField()),
                ('PurchasePrice', models.IntegerField()),
                ('OldSalePrice', models.IntegerField()),
                ('CurrSalePrice', models.IntegerField()),
                ('TotalSalePrice', models.IntegerField()),
                ('SepcialDiscount', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('ProductDeliveryStatus', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('TotalSalePrice', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Customername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('SaleInvoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.salemaster')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitQty', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('TotalSalePrice', models.IntegerField()),
                ('SepcialDiscount', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('ProductDeliveryStatus', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('SaleInvoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.salemaster')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('TotalSalePrice', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('SaleInvoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.salemaster')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseInvoiceNumber', models.CharField(max_length=150)),
                ('UnitQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('Image', models.ImageField(upload_to='Product_Purchase_History/')),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('PurchaseInvoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.purchasemaster')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMultipleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='product_multi_image/')),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('u_dt', models.DateTimeField(auto_now_add=True)),
                ('u_usr', models.CharField(max_length=150)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
            ],
        ),
        migrations.AddField(
            model_name='productlist',
            name='Size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size'),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district'),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='Thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.thana'),
        ),
        migrations.CreateModel(
            name='CustomerLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogingTime', models.DateTimeField(auto_now=True)),
                ('LogOutTime', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district'),
        ),
        migrations.AddField(
            model_name='area',
            name='Thana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.thana'),
        ),
    ]
