# Generated by Django 4.2.6 on 2023-10-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisiontCode', models.IntegerField(blank=True, null=True)),
                ('divisiontName', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'District',
            },
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': 'Area'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Color'},
        ),
        migrations.AlterModelOptions(
            name='customerloginhistory',
            options={'verbose_name_plural': 'CustomerLoginHistory'},
        ),
        migrations.AlterModelOptions(
            name='customershippingaddress',
            options={'verbose_name_plural': 'CustomerShippingAddress'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name_plural': 'District'},
        ),
        migrations.AlterModelOptions(
            name='productlist',
            options={'verbose_name_plural': 'ProductList'},
        ),
        migrations.AlterModelOptions(
            name='productmultipleimage',
            options={'verbose_name_plural': 'ProductMultipleImage'},
        ),
        migrations.AlterModelOptions(
            name='purchasedetail',
            options={'verbose_name_plural': 'PurchaseDetail'},
        ),
        migrations.AlterModelOptions(
            name='purchasemaster',
            options={'verbose_name_plural': 'PurchaseMaster'},
        ),
        migrations.AlterModelOptions(
            name='returndetail',
            options={'verbose_name_plural': 'ReturnDetail'},
        ),
        migrations.AlterModelOptions(
            name='returnmaster',
            options={'verbose_name_plural': 'ReturnMaster'},
        ),
        migrations.AlterModelOptions(
            name='salehistory',
            options={'verbose_name_plural': 'SaleHistory'},
        ),
        migrations.AlterModelOptions(
            name='salemaster',
            options={'verbose_name_plural': 'SaleMaster'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'Size'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name_plural': 'Supplier'},
        ),
        migrations.AlterModelOptions(
            name='thana',
            options={'verbose_name_plural': 'Thana'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name_plural': 'WishList'},
        ),
        migrations.AddField(
            model_name='district',
            name='DistrictCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='DivisionName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thana',
            name='DistrictName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thana',
            name='DivisionName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='thana',
            name='ThanaCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thana',
            name='deviveryCharge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='DistrictName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thana',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district'),
        ),
        migrations.AlterField(
            model_name='thana',
            name='ThanaName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.division'),
        ),
        migrations.AddField(
            model_name='thana',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.division'),
        ),
    ]
