# Generated by Django 4.2.6 on 2023-10-21 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0002_division_alter_area_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customershippingaddress',
            name='AreaName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='DistrictName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.division'),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='DivisionName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customershippingaddress',
            name='ThanaName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='AreaName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district'),
        ),
        migrations.AlterField(
            model_name='area',
            name='Thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.thana'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='Address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='Address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.area'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='Customername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district'),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='Email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='MobileNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customershippingaddress',
            name='Thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.thana'),
        ),
        migrations.AlterField(
            model_name='size',
            name='Brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand'),
        ),
        migrations.AlterField(
            model_name='size',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category'),
        ),
        migrations.AlterField(
            model_name='size',
            name='SizeName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
