# Generated by Django 4.2.6 on 2023-10-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0003_customershippingaddress_areaname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmultipleimage',
            name='ProductCode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='productmultipleimage',
            name='ProductName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
