# Generated by Django 4.2.6 on 2023-10-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0007_wishlist_productcode_wishlist_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerloginhistory',
            name='Customername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
