# Generated by Django 4.2.6 on 2023-10-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0008_customerloginhistory_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='BrandName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
