# Generated by Django 4.2.6 on 2023-10-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0009_productlist_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='CategoryName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='ColorName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='SizeName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
