# Generated by Django 4.2.6 on 2023-10-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0013_returndetail_brandname_returndetail_categoryname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='divisiontCode',
            new_name='divisionCode',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='divisiontName',
            new_name='divisionName',
        ),
    ]
