# Generated by Django 4.2.6 on 2023-10-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0014_rename_divisiontcode_division_divisioncode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name_plural': 'Division'},
        ),
        migrations.AlterField(
            model_name='productlist',
            name='UnitCurrSalePrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='UnitOldSalePrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='UnitPreviousStock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='UnitPurchasePrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='UnitStockInHand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productmultipleimage',
            name='u_usr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
