# Generated by Django 4.2.6 on 2023-10-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0015_alter_division_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemaster',
            name='ProductDeliveryStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
