# Generated by Django 4.2.6 on 2023-11-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0016_alter_salemaster_productdeliverystatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderInvoiceNumber', models.CharField(max_length=150)),
                ('Qty', models.IntegerField()),
                ('TotalPurchasePrice', models.IntegerField()),
                ('PurchasePrice', models.IntegerField()),
                ('OldSalePrice', models.IntegerField()),
                ('CurrSalePrice', models.IntegerField()),
                ('TotalSalePrice', models.IntegerField()),
                ('SepcialDiscount', models.IntegerField()),
                ('TotalPrice', models.IntegerField()),
                ('ProductDeliveryStatus', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
            options={
                'verbose_name_plural': 'OrderMaster',
            },
        ),
        migrations.CreateModel(
            name='OrderDeatail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('TotalSalePrice', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Customername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
                ('OrderInvoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.ordermaster')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
            options={
                'verbose_name_plural': 'OrderDeatail',
            },
        ),
    ]
