# Generated by Django 4.2.6 on 2023-11-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0017_ordermaster_orderdeatail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermaster',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='ordermaster',
            name='Size',
        ),
        migrations.DeleteModel(
            name='OrderDeatail',
        ),
        migrations.DeleteModel(
            name='OrderMaster',
        ),
    ]
