# Generated by Django 4.2.6 on 2023-11-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0019_ordermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(blank=True, max_length=8, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('UnitQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('TotalSalePrice', models.IntegerField()),
                ('BrandName', models.CharField(blank=True, max_length=100, null=True)),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('ColorName', models.CharField(blank=True, max_length=100, null=True)),
                ('SizeName', models.CharField(blank=True, max_length=100, null=True)),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Customername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
                ('OrderInvoiceNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.ordermaster')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productlist')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
            options={
                'verbose_name_plural': 'OrderDetail',
            },
        ),
    ]
