# Generated by Django 4.2.6 on 2023-11-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0020_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.division'),
        ),
        migrations.AddField(
            model_name='area',
            name='deviveryCharge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
