# Generated by Django 4.2.6 on 2023-11-23 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0024_delete_productlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitPreviousStock', models.IntegerField(blank=True, null=True)),
                ('UnitPurchasePrice', models.IntegerField(blank=True, null=True)),
                ('UnitCurrSalePrice', models.IntegerField(blank=True, null=True)),
                ('UnitOldSalePrice', models.IntegerField(blank=True, null=True)),
                ('UnitStockInHand', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='product_images/')),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('u_dt', models.DateTimeField(auto_now_add=True)),
                ('u_usr', models.CharField(max_length=150)),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
            options={
                'verbose_name_plural': 'ProductList',
            },
        ),
    ]
