# Generated by Django 4.2.6 on 2023-11-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0025_productdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetail',
            options={'verbose_name_plural': 'ProductDetail'},
        ),
    ]
