# Generated by Django 4.2.6 on 2023-11-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0027_productmultipleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseInvoiceNumber', models.CharField(max_length=150)),
                ('UnitQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('BrandName', models.CharField(blank=True, max_length=100, null=True)),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('ColorName', models.CharField(blank=True, max_length=100, null=True)),
                ('SizeName', models.CharField(blank=True, max_length=100, null=True)),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productdetail')),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier')),
            ],
            options={
                'verbose_name_plural': 'PurchaseMaster',
            },
        ),
    ]
