# Generated by Django 4.2.6 on 2023-12-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0029_wishlist_salemaster_salehistory_returnmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
    ]
