# Generated by Django 4.2.6 on 2023-12-09 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0032_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermaster',
            old_name='OrderInvoiceNumber',
            new_name='OrderInvoiceNo',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='PurchaseInvoiceNumber',
            new_name='PurchaseInvoiceNo',
        ),
    ]
