# Generated by Django 4.2.6 on 2023-12-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0033_rename_orderinvoicenumber_ordermaster_orderinvoiceno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='OrderInvoiceNumber',
            new_name='OrderInvoiceNo',
        ),
        migrations.RenameField(
            model_name='purchasemaster',
            old_name='PurchaseInvoiceNumber',
            new_name='PurchaseInvoiceNo',
        ),
        migrations.RenameField(
            model_name='returndetail',
            old_name='SaleInvoiceNumber',
            new_name='SaleInvoiceNo',
        ),
        migrations.RenameField(
            model_name='returnmaster',
            old_name='SaleInvoiceNumber',
            new_name='SaleInvoiceNo',
        ),
        migrations.RenameField(
            model_name='salehistory',
            old_name='SaleInvoiceNumber',
            new_name='SaleInvoiceNo',
        ),
        migrations.RenameField(
            model_name='salemaster',
            old_name='SaleInvoiceNumber',
            new_name='SaleInvoiceNo',
        ),
    ]
