# Generated by Django 4.2.6 on 2023-12-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0035_profitaftersale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profitaftersale',
            old_name='SaleInvoiceNumber',
            new_name='SaleInvoiceNo',
        ),
    ]
