# Generated by Django 4.2.6 on 2023-12-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0036_rename_saleinvoicenumber_profitaftersale_saleinvoiceno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasemaster',
            old_name='UnitCurrSalePrice',
            new_name='PurchaseQty',
        ),
        migrations.RenameField(
            model_name='purchasemaster',
            old_name='UnitOldSalePrice',
            new_name='TotalPurchasePrice',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='BrandName',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='CategoryName',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='ColorName',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='ProductCode',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='Size',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='SizeName',
        ),
        migrations.RemoveField(
            model_name='purchasemaster',
            name='UnitQty',
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='PurchaseInvoiceNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier'),
        ),
    ]
