# Generated by Django 4.2.6 on 2023-12-09 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0037_rename_unitcurrsaleprice_purchasemaster_purchaseqty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='UnitOldSalePrice',
            new_name='Qty',
        ),
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='UnitQty',
            new_name='totalPurchasePrice',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='BrandName',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='CategoryName',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='ColorName',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='Size',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='SizeName',
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='Productdtl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productdetail'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='PurchaseMaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.purchasemaster'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='ProductCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='PurchaseInvoiceNo',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier'),
        ),
        migrations.CreateModel(
            name='AvgPurchaseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(blank=True, max_length=10, null=True)),
                ('StockInHand', models.IntegerField()),
                ('AvgCost', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('u_dt', models.DateTimeField(auto_now=True)),
                ('u_usr', models.CharField(max_length=150)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
            ],
            options={
                'verbose_name_plural': 'AvgPurchaseCost',
            },
        ),
    ]
