# Generated by Django 4.2.6 on 2023-12-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0038_rename_unitoldsaleprice_purchasedetail_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='u_dt',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='u_usr',
        ),
    ]
