# Generated by Django 4.2.6 on 2023-12-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0039_remove_productdetail_u_dt_remove_productdetail_u_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='u_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='u_usr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
