# Generated by Django 4.2.6 on 2023-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0040_productdetail_u_dt_productdetail_u_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='i_usr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
