# Generated by Django 4.2.6 on 2023-12-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0041_alter_productdetail_i_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='i_usr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='u_usr',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
