# Generated by Django 4.2.6 on 2023-12-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0045_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AreaName', models.CharField(blank=True, max_length=100, null=True)),
                ('deviveryCharge', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Area',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DistrictCode', models.IntegerField(blank=True, null=True)),
                ('DistrictName', models.CharField(blank=True, max_length=100, null=True)),
                ('DivisionName', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'District',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisionCode', models.IntegerField(blank=True, null=True)),
                ('divisionName', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Division',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SupplierName', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThanaCode', models.IntegerField(blank=True, null=True)),
                ('ThanaName', models.CharField(blank=True, max_length=200, null=True)),
                ('DistrictName', models.CharField(blank=True, max_length=100, null=True)),
                ('DivisionName', models.CharField(blank=True, max_length=100, null=True)),
                ('deviveryCharge', models.IntegerField(blank=True, null=True)),
                ('District', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district')),
                ('Division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.division')),
            ],
            options={
                'verbose_name_plural': 'Thana',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.division'),
        ),
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(blank=True, max_length=50, null=True)),
                ('MobileNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Address1', models.CharField(blank=True, max_length=200, null=True)),
                ('Address2', models.CharField(blank=True, max_length=200, null=True)),
                ('DivisionName', models.CharField(blank=True, max_length=100, null=True)),
                ('DistrictName', models.CharField(blank=True, max_length=100, null=True)),
                ('ThanaName', models.CharField(blank=True, max_length=100, null=True)),
                ('AreaName', models.CharField(blank=True, max_length=100, null=True)),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('u_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('Area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.area')),
                ('District', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district')),
                ('Division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.division')),
                ('Thana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.thana')),
            ],
            options={
                'verbose_name_plural': 'CustomerShippingAddress',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.district'),
        ),
        migrations.AddField(
            model_name='area',
            name='Division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.division'),
        ),
        migrations.AddField(
            model_name='area',
            name='Thana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.thana'),
        ),
    ]
