# Generated by Django 4.2.6 on 2023-12-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0046_area_district_division_supplier_thana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(blank=True, max_length=10, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('UnitPurchasePrice', models.IntegerField(blank=True, null=True)),
                ('UnitCurrSalePrice', models.IntegerField(blank=True, null=True)),
                ('UnitOldSalePrice', models.IntegerField(blank=True, null=True)),
                ('UnitStockInHand', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='product_image/')),
                ('productDesc', models.TextField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('u_dt', models.DateTimeField(auto_now_add=True)),
                ('u_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('Brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(blank=True, max_length=10, null=True)),
                ('UnitPreviousStock', models.IntegerField(blank=True, null=True)),
                ('UnitPurchasePrice', models.IntegerField(blank=True, null=True)),
                ('UnitCurrSalePrice', models.IntegerField(blank=True, null=True)),
                ('UnitOldSalePrice', models.IntegerField(blank=True, null=True)),
                ('UnitStockInHand', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='product_images/')),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('u_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('u_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('Color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
                ('Size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
            options={
                'verbose_name_plural': 'ProductDetail',
            },
        ),
    ]
