# Generated by Django 4.2.6 on 2023-12-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0047_products_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseInvoiceNo', models.CharField(blank=True, max_length=10, null=True)),
                ('PurchaseQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('TotalPurchasePrice', models.IntegerField()),
                ('InvoiceDate', models.DateField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier')),
            ],
            options={
                'verbose_name_plural': 'PurchaseMaster',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurInvoiceNo', models.CharField(blank=True, max_length=10, null=True)),
                ('PurchaseQty', models.IntegerField()),
                ('PurchasePrice', models.IntegerField()),
                ('InvoiceDate', models.DateField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier')),
            ],
            options={
                'verbose_name_plural': 'Invoice',
            },
        ),
    ]
