# Generated by Django 4.2.6 on 2023-12-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0048_purchasemaster_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PurchaseInvoiceNo', models.CharField(max_length=12)),
                ('ProductCode', models.CharField(blank=True, max_length=10, null=True)),
                ('Qty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('totalPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
                ('Productdtl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productdetail')),
                ('PurchaseMaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.purchasemaster')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier')),
            ],
            options={
                'verbose_name_plural': 'PurchaseDetail',
            },
        ),
        migrations.CreateModel(
            name='AvgPurchaseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductCode', models.CharField(blank=True, max_length=10, null=True)),
                ('StockInHand', models.IntegerField(blank=True, null=True)),
                ('AvgCost', models.IntegerField(blank=True, null=True)),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('u_dt', models.DateTimeField(auto_now=True)),
                ('u_usr', models.CharField(blank=True, max_length=150, null=True)),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
            ],
            options={
                'verbose_name_plural': 'AvgPurchaseCost',
            },
        ),
    ]
