# Generated by Django 4.2.6 on 2023-12-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0051_salemaster_salehistory_returnmaster_profitaftersale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(max_length=255)),
                ('key2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitQty', models.IntegerField()),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productdetail')),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
            ],
            options={
                'verbose_name_plural': 'WishList',
            },
        ),
        migrations.CreateModel(
            name='ReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitQty', models.IntegerField()),
                ('UnitPurchasePrice', models.IntegerField()),
                ('UnitCurrSalePrice', models.IntegerField()),
                ('UnitOldSalePrice', models.IntegerField()),
                ('TotalSalePrice', models.IntegerField()),
                ('BrandName', models.CharField(blank=True, max_length=100, null=True)),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('ColorName', models.CharField(blank=True, max_length=100, null=True)),
                ('SizeName', models.CharField(blank=True, max_length=100, null=True)),
                ('i_dt', models.DateTimeField(auto_now=True)),
                ('i_usr', models.CharField(max_length=150)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.brand')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.category')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.color')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.productdetail')),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
                ('SaleInvoiceNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.salemaster')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
            options={
                'verbose_name_plural': 'ReturnDetail',
            },
        ),
        migrations.CreateModel(
            name='proddtl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.products')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.size')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(blank=True, max_length=50, null=True)),
                ('LogingTime', models.DateTimeField(auto_now=True)),
                ('LogOutTime', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.customershippingaddress')),
            ],
            options={
                'verbose_name_plural': 'CustomerLoginHistory',
            },
        ),
    ]
