# Generated by Django 4.2.6 on 2023-12-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0053_alter_invoice_invoicedate_productmultipleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
