# Generated by Django 4.2.6 on 2023-12-15 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_adminPanel', '0054_alter_invoice_invoicedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Supplier',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='PurchaseInvoiceNo',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='PurchaseMaster',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Suppli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.supplier'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='PurInvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_adminPanel.invoice'),
        ),
    ]
